swagger: '2.0'
info:
  version: 1.0.0
  title: HTTP API for parsing tachograph file
  description: HTTP API for parsing tachograph file
  termsOfService: ''
paths:
  /createAzureResources:
    post:
      description: parse given tachograph file (mass memory or drivercard file)
      summary: parse given tachograph file (mass memory or drivercard file)
      consumes:
        - application/json
      parameters:
        - in: body
          name: requestBody
          schema:
            $ref: '#/definitions/AzCodegenRequest'
      responses:
        '200':
          description: OK
          schema:
            type: string
definitions:
  AzCodegenRequest:
    description: parsed file result
    type: object
    properties:
      appConfig:
        $ref: '#/definitions/appConfig'
      azAccount:
        $ref: '#/definitions/azAccount'
      graph:
        $ref: '#/definitions/graph'
  appConfig:
    type: object
    properties:
      localDeploymentOnly:
        type: boolean
  azAccount:
    type: object
    properties:
      subscription:
        type: string
      resourceGroupName:
        type: string
      resourceGroupLocation:
        type: string
      appServicePlanName:
        type: string
      servicePrincipalName:
        type: string
  graph:
    type: object
    properties:
      nodes:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            type:
              type: string
      edges:
        type: array
        items:
          type: object
          properties:
            node1:
              type: string
            node2:
              type: string
            type:
              type: string