package com.werner.bl.codegeneration.generators.projectlevel;

import com.werner.bl.codegeneration.generators.classlevel.ClassGenerator;
import com.werner.bl.codegeneration.model.FunctionApp;
import com.werner.bl.codegeneration.model.FunctionAppClient;
import com.werner.bl.codegeneration.model.FunctionAppTrigger;
import com.werner.helper.FileUtil;
import com.werner.powershell.PowershellMavenAzFunCaller;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
@AllArgsConstructor
public class ProjectGenerator {

    private final FileUtil fileUtil;

    private final ClassGenerator classGenerator;

    private final PowershellMavenAzFunCaller powershellMavenAzFunCaller;

    private final PomGenerator pomGenerator;

    public void generateProject(FunctionApp functionApp, String resolvedTempDir) throws Exception {
        Project project = initProject(functionApp, resolvedTempDir);

        powershellMavenAzFunCaller.generateProject(project);

        writeClassFile(project, functionApp.getTriggerList(), functionApp.getClientList());
        writePomFile(project, functionApp.getTriggerList(), functionApp.getClientList(), functionApp.getAdditionalProperties());

        // TODO App Settings
        // TODO Mapping in ComponentLevelAnnotation

        powershellMavenAzFunCaller.buildProject(project);
        powershellMavenAzFunCaller.deployProject(project);
    }

    private Project initProject(FunctionApp functionApp, String resolvedTempDir) {
        Project result = new Project();

        String mavenArtifactId = functionApp.getFunctionAppName();
        result.setArtifactId(mavenArtifactId);

        String mavenGroupId = "com.werner";
        result.setGroupId(mavenGroupId);

        result.setProjectRoot(resolvedTempDir + "\\" + mavenArtifactId);

        return result;
    }

    private void writeClassFile(Project project, List<FunctionAppTrigger> triggers, List<FunctionAppClient> clients) {
        String classCode = classGenerator.generateClassCode(triggers, clients, project);

        String classFilePath = project.getProjectRoot() + "\\src\\main\\java\\com\\werner\\" + project.getArtifactId() + "\\GeneratedClass.java";
        fileUtil.writeContentToFile(classFilePath, classCode);

        // this gets generated by default during maven archetype task
        String unnessecaryClassFilePath = project.getProjectRoot() + "\\src\\main\\java\\com\\werner\\" + project.getArtifactId() + "\\Function.java";
        fileUtil.deleteFile(unnessecaryClassFilePath);
    }

    private void writePomFile(Project project, List<FunctionAppTrigger> triggers, List<FunctionAppClient> clients, Map<String, String> additionalProperties) {
        String pomCode = pomGenerator.generateCode(project, triggers, clients, additionalProperties);
        String pomPath = project.getProjectRoot() + "\\pom.xml";

        fileUtil.writeContentToFile(pomPath, pomCode);
    }
}
