# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Build with Maven
        run: mvn clean package
      - name: Archive Jar
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Jar
          path: target/GenerationProject-1.0-SNAPSHOT.jar
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2.1.1